export enum DOCUMENT_SOURCE {
  AI_ARTIFACT = "AI_ARTIFACT",
  USER_UPLOADED = "USER_UPLOADED"
}

export enum CHAT_ACTOR {
  USER = "USER",
  ASSISTANT = "ASSISTANT"
}

export enum DOCUMENT_EVENT_TYPE {
  CREATED = "CREATED",
  UPLOADED = "UPLOADED",
  MODIFIED = "MODIFIED"
}
